//! Snapshot of the model-request identity held by a loaded Codex thread.

use serde::Serialize;

/// Identity fields generated by a loaded thread for one or more model requests.
///
/// These values are read-only snapshots of the real thread/session/turn metadata.
/// Consumers such as local proxies should not synthesize these fields locally.
#[derive(Clone, Debug, Serialize)]
pub struct ModelRequestIdentity {
    pub installation_id: String,
    pub session_id: String,
    pub thread_id: String,
    pub window_id: String,
    pub parent_thread_id: Option<String>,
    pub turn_id: Option<String>,
    pub root_turn_id: Option<String>,
    pub parent_turn_id: Option<String>,
}
