// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestId } from "../RequestId";
import type { RawResponseStreamEvent } from "./RawResponseStreamEvent";

/**
 * Opaque upstream transport data for one streaming `turn/start.rawResponses` RPC.
 * Sent only to the requesting connection. The terminal RPC result/error ends the stream.
 */
export type RawResponseStreamNotification = { requestId: RequestId, event: RawResponseStreamEvent, };
