// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RawResponseStreamEvent = { "type": "started", status: number, headers: { [key in string]?: string }, } | { "type": "chunk",
/**
 * Exact upstream octets, at most 16 KiB per notification. No UTF-8/SSE decoding.
 */
data: Array<number>, };
