// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadModelIdentity = { threadId: string, sessionId: string, installationId: string, windowId: string, parentThreadId: string | null, turnId: string | null, rootTurnId: string | null, parentTurnId: string | null, };
